// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 TechFlow IT
//
// QR detection and batch splitting with the synthetic PDFs in tests/fixtures
// (generated by tools/make-fixtures.py).

const test = require('node:test');
const assert = require('node:assert/strict');
const path = require('path');

const { leseQr } = require('../qr.js');
const { dekodiereJpeg } = require('../jpeg.js');
const { seitenBilder, teileNachQr, jpegMasse } = require('../pdf-split.js');

const fixture = (name) => path.join(__dirname, 'fixtures', name);

// Same reader as in server.js: JPEG pages are decoded first, CCITT pages arrive as greyscale.
function reader(page) {
  if (page.art === 'grau') return leseQr(page.grauDaten, page.breite, page.hoehe);
  const img = dekodiereJpeg(page.jpeg);
  return img.fehler ? null : leseQr(img.grau, img.breite, img.hoehe);
}

test('reads the QR code of a single JPEG page', () => {
  const pages = seitenBilder(fixture('single-jpeg.pdf'));
  assert.equal(pages.length, 1);
  assert.equal(pages[0].art, 'jpeg');
  assert.deepEqual(jpegMasse(pages[0].jpeg), { breite: 827, hoehe: 1169 });
  assert.equal(reader(pages[0]), 'DOC-1001');
});

test('reads an unevenly blackened, noisy scan', () => {
  const [page] = seitenBilder(fixture('uneven-jpeg.pdf'));
  assert.equal(reader(page), 'E-5005');
});

test('returns null for a page without a code', () => {
  const pages = seitenBilder(fixture('no-code-jpeg.pdf'));
  assert.equal(pages.length, 2);
  pages.forEach((p) => assert.equal(reader(p), null));
});

test('splits a JPEG batch scan at the pages with QR codes', () => {
  const result = teileNachQr(fixture('batch-jpeg.pdf'), reader);
  assert.equal(result.ok, true);
  assert.deepEqual(result.dokumente.map((d) => [d.qrWert, d.seitenNummern]), [
    ['A-1001', [1, 2]],
    ['B-2002', [3]],
    ['C-3003', [4, 5]],
  ]);
  for (const doc of result.dokumente) {
    assert.ok(Buffer.isBuffer(doc.pdf));
    assert.match(doc.pdf.subarray(0, 8).toString('latin1'), /^%PDF-1\.\d/);
    // Every part is a valid PDF again and can itself be read page by page
    assert.match(doc.pdf.subarray(-8).toString('latin1'), /%%EOF\s*$/);
  }
});

test('the parts contain the original page images byte for byte', () => {
  const original = seitenBilder(fixture('batch-jpeg.pdf'));
  const result = teileNachQr(fixture('batch-jpeg.pdf'), reader);
  const firstPart = result.dokumente[0].pdf;
  assert.ok(firstPart.includes(original[0].jpeg), 'page 1 image copied unchanged');
  assert.ok(firstPart.includes(original[1].jpeg), 'page 2 image copied unchanged');
});

test('splits a CCITT Group 4 batch scan', () => {
  const pages = seitenBilder(fixture('batch-ccitt.pdf'));
  assert.deepEqual(pages.map((p) => p.art), ['grau', 'grau', 'grau']);
  const result = teileNachQr(fixture('batch-ccitt.pdf'), reader);
  assert.equal(result.ok, true);
  assert.deepEqual(result.dokumente.map((d) => [d.qrWert, d.seitenNummern]), [
    ['F-6006', [1, 2]],
    ['G-7007', [3]],
  ]);
});

test('keeps or discards leading pages without a code', () => {
  const kept = teileNachQr(fixture('leading-pages-jpeg.pdf'), reader);
  assert.deepEqual(kept.dokumente.map((d) => [d.qrWert, d.seitenNummern]), [[null, [1]], ['D-4004', [2, 3]]]);
  const dropped = teileNachQr(fixture('leading-pages-jpeg.pdf'), reader, { vorspannVerwerfen: true });
  assert.deepEqual(dropped.dokumente.map((d) => [d.qrWert, d.seitenNummern]), [['D-4004', [2, 3]]]);
});

test('does not split when no page carries a code', () => {
  const result = teileNachQr(fixture('no-code-jpeg.pdf'), reader);
  assert.equal(result.ok, false);
  assert.match(result.meldung, /No QR code was found on any of the 2 pages/);
});
